#!/usr/bin/env bash
# Infinite loop that prints a message and reacts to SIGTERM

trap 'echo "I am invincible!!!"' SIGTERM

# Notify checker that trap is set correctly
echo "OK"

while true; do
  echo "To infinity and beyond"
  sleep 2
done
