#!/usr/bin/env bash
# Script that traps SIGTERM and refuses to die

# Trap SIGTERM (15) and print the message
trap 'echo "I am invincible!!!"' SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
